//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Website.Localization.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Outlook (or other).
        /// </summary>
        public static string AddToCalendar {
            get {
                return ResourceManager.GetString("AddToCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Google Calendar.
        /// </summary>
        public static string AddToGoogleCalendar {
            get {
                return ResourceManager.GetString("AddToGoogleCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,
        ///
        ///Thank you for having answered our wedding invitation.  We regret that you will not be able to attend; your presence will be missed. 
        ///
        ///We invite you to contact us in case of error or for any other question.
        ///
        ///Regards,
        ///
        ///Sheetal and Laurent.
        /// </summary>
        public static string EmailConfirmedNo {
            get {
                return ResourceManager.GetString("EmailConfirmedNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,
        ///
        ///Thank you for having confirmed your attendance ({Guests} guest(s)) at our wedding.  It’s a pleasure to have you join us. 
        ///
        ///We invite you to contact us in case of questions or specific needs.
        ///
        ///See you soon!
        ///
        ///Sheetal and Laurent.
        /// </summary>
        public static string EmailConfirmedYes {
            get {
                return ResourceManager.GetString("EmailConfirmedYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,
        ///
        ///Many of you have expressed a desire to see the pictures taken during the evening. Therefore, we created a website for you to view them: http://photos.lebeaumartin.com/Wedding
        ///
        ///The website contains 11 (!!) photo galleries, each one taken by a different photographer. There are eight galleries covering the wedding, one small gallery for the installation before the wedding and two galleries for the evening on the day before the wedding (the henna party, Mendhi).
        ///
        ///One or two more galleries will be  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EmailPhotosBody {
            get {
                return ResourceManager.GetString("EmailPhotosBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wedding Photos.
        /// </summary>
        public static string EmailPhotosSubject {
            get {
                return ResourceManager.GetString("EmailPhotosSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your invitation code:.
        /// </summary>
        public static string EnterInviteCode {
            get {
                return ResourceManager.GetString("EnterInviteCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information, do not hesitate to.
        /// </summary>
        public static string ForMoreInformation {
            get {
                return ResourceManager.GetString("ForMoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many will you be?.
        /// </summary>
        public static string HowManyWillYouBe {
            get {
                return ResourceManager.GetString("HowManyWillYouBe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;lead&quot;&gt;
        ///    Your love and friendship have helped us become who we are.
        ///&lt;br&gt;
        ///    Together with our parents,
        ///    we invite you to share our joy
        ///    and support our love,
        ///&lt;br&gt;
        ///    as two best friends become husband and wife.
        ///&lt;br&gt;
        ///    Please join us for a celebration of love, friendship,
        ///    laughter and family.
        ///&lt;br&gt;
        ///    Fabulous food, fun, and festivities will follow!
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    &amp;mdash; Laurent &amp;amp; Sheetal
        ///&lt;/p&gt;.
        /// </summary>
        public static string IntroHtml {
            get {
                return ResourceManager.GetString("IntroHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code.
        /// </summary>
        public static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {InformalName},
        ///
        ///It is our pleasure to invite you to our wedding, which will take place on August 24 at 5 PM. 
        ///
        ///A detailed invitation is waiting for you on our web site: http://www.sheetalandlaurent.com/invitations/{Id}
        ///It contains all the information about the event along with an RSVP form.
        ///
        ///Please let us know before July 31 if you can attend.
        ///
        ///We hope to see you at our wedding!
        ///
        ///Laurent and Sheetal.
        /// </summary>
        public static string InvitationEmailBody {
            get {
                return ResourceManager.GetString("InvitationEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wedding Invitation.
        /// </summary>
        public static string InvitationEmailSubject {
            get {
                return ResourceManager.GetString("InvitationEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation for:.
        /// </summary>
        public static string InvitationFor {
            get {
                return ResourceManager.GetString("InvitationFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just show me a map.
        /// </summary>
        public static string MapTitle {
            get {
                return ResourceManager.GetString("MapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you lost your invitation code, please.
        /// </summary>
        public static string NoInviteCode {
            get {
                return ResourceManager.GetString("NoInviteCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note:.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitee: {FullName}
        ///Email: {Email}
        ///Will attend? {IsAttending}
        ///Guests? {Guests} / {AllowedGuests}
        ///Note: {Note}.
        /// </summary>
        public static string NotificationBody {
            get {
                return ResourceManager.GetString("NotificationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {InformalName} replied to the wedding invitation!.
        /// </summary>
        public static string NotificationSubject {
            get {
                return ResourceManager.GetString("NotificationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The happy couple.
        /// </summary>
        public static string PhotoAlt {
            get {
                return ResourceManager.GetString("PhotoAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,
        ///
        ///Just a quick reminder that our wedding is next week, Saturday August 24th! You are expected at 5 PM; the ceremony will start shortly after.
        ///
        ///The address:
        ///Le Manoir
        ///5319 avenue Notre-Dame-de-Grâce
        ///Montréal, Québec
        ///H4A 1L2 Canada 
        ///
        ///Google Maps: http://goo.gl/fA4zVc
        ///
        ///We can’t wait to see you all!
        ///
        ///Regards,
        ///
        ///Sheetal and Laurent.
        /// </summary>
        public static string ReminderBody {
            get {
                return ResourceManager.GetString("ReminderBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder: Wedding next week!.
        /// </summary>
        public static string ReminderSubject {
            get {
                return ResourceManager.GetString("ReminderSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please submit your answer &lt;strong&gt;before July 31th, 2013.&lt;/strong&gt;.
        /// </summary>
        public static string RsvpDeadline {
            get {
                return ResourceManager.GetString("RsvpDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your response has successfully been sent. Thank you!.
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        public static string SwitchLanguage {
            get {
                return ResourceManager.GetString("SwitchLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.sheetaletlaurent.com.
        /// </summary>
        public static string SwitchLanguageUrl {
            get {
                return ResourceManager.GetString("SwitchLanguageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheetal &amp; Laurent are getting married!.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View larger map.
        /// </summary>
        public static string ViewLargerMap {
            get {
                return ResourceManager.GetString("ViewLargerMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday,&lt;br /&gt;
        ///&lt;span class=&quot;huge label&quot;&gt;24&lt;/span&gt;&lt;br /&gt;
        ///August 2013 at &lt;strong&gt;17:00&lt;/strong&gt;.
        /// </summary>
        public static string WhenHtml {
            get {
                return ResourceManager.GetString("WhenHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When?.
        /// </summary>
        public static string WhenTitle {
            get {
                return ResourceManager.GetString("WhenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Le Manoir&lt;/strong&gt;&lt;br /&gt;
        ///5319 avenue Notre-Dame-de-Grâce&lt;br /&gt;
        ///Montréal, Québec&lt;br /&gt;
        ///H4A 1L2 Canada.
        /// </summary>
        public static string WhereHtml {
            get {
                return ResourceManager.GetString("WhereHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where?.
        /// </summary>
        public static string WhereTitle {
            get {
                return ResourceManager.GetString("WhereTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will you be attending?.
        /// </summary>
        public static string WillYouBeAttending {
            get {
                return ResourceManager.GetString("WillYouBeAttending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your invitation.
        /// </summary>
        public static string YourInvitation {
            get {
                return ResourceManager.GetString("YourInvitation", resourceCulture);
            }
        }
    }
}
